routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('reportPreview', 'center_reportController@reportPreview');
Route::group(['middleware'=>'auth'],function(){
    Route::get('/', function () {
        return view('home');
    })->name('home');
//    Route::any('user/create','UserController@create')->name('user.store');
//    Route::get('user','UserController@index')->name('user.index');
    Route::resource('user', 'UserController');
    Route::resource('patientrequests', 'PatientRequestController');
    Route::any('confirm', 'PatientRequestController@confirmRequestEdit');
    Route::any('updateconfirm', 'PatientRequestController@confirmRequestUpdate');
    Route::any('result', 'PatientRequestController@resultCreate');
    Route::any('resultStore', 'PatientRequestController@resultStore');
    Route::resource('radiologytypecategories','RadiologyTypeCategoryController');
    Route::resource('radiologytypes','RadiologyTypeController');
    Route::resource('centers','CentersController');
    /* Lab test*/
    Route::resource('labrequests', 'RequestController');
    Route::any('updateRefuserequest','RequestController@updateRefuse')->name('requests.updateRefuserequest');
    Route::any('sortnamerequest','RequestController@sortname')->name('requests.sortnamerequest');
    Route::any('sortdaterequest','RequestController@sortdate')->name('requests.sortdaterequest');
    Route::any('sortlocationrequest','RequestController@sortlocation')->name('requests.sortlocationrequest');
    Route::any('sortstatusrequest','RequestController@sortstatus')->name('requests.sortstatusrequest');
    Route::any('storerequest','RequestController@sortstatus')->name('requests.storerequest');
    
    /*End Lab test*/
    Route::any('/reportreportAjax','center_reportController@reportAjax');

    Route::resource('', 'HomeController');
    Route::resource('centerresponses', 'CenterResponseController');
    Route::any('updateRefuse','PatientRequestController@updateRefuse')->name('patientrequests.updateRefuse');
    Route::any('sortname','PatientRequestController@sortname')->name('patientrequests.sortname');
    Route::any('sortdate','PatientRequestController@sortdate')->name('patientrequests.sortdate');
    Route::any('sortlocation','PatientRequestController@sortlocation')->name('patientrequests.sortlocation');
    Route::any('sortstatus','PatientRequestController@sortstatus')->name('patientrequests.sortstatus');

    Route::any('/reportAjax','PatientRequestController@reportAjax');
    Route::any('/notifiy','PatientRequestController@notifiy');
    Route::any('/notifiycenter','CenterResponseController@notifiycenter');
    Route::any('/notifiyresult','CenterResponseController@notifiyresult');

    Route::get('reports/statusgroup','ReportsController@statusReports')->name('reports.statusgroup');

Route::any('/reportuploads','PatientRequestController@reportuploads');

    Route::resource('urlgroups', 'UrlGroupController');
    Route::resource('urls', 'UrlController');
    Route::resource('usertypes', 'UserTypeController');
    Route::any('batchUpdate','UserTypeController@batchUpdate')->name('usertypes.batchUpdate');
    Route::post('language-switcher','LanguageController@switchLanguage');
    Route::post('/language/',array(
            'before' => 'csrf' ,
            'as' => 'language-switcher' ,
            'uses' => 'LanguageController@switchLanguage'
        )
    );
});


Route::get('/login', function () {
    return view('auth.login');
});

Route::group(['namespace'=>'Auth'],function(){
    Route::post('/login', ['uses'=>'LoginController@login'])->name('login.post');
    Route::get('/logout', ['uses'=>'LoginController@logout'])->name('auth.logout');
});

app/RadiologyTypeCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RadiologyTypeCategory extends Model
{
    protected $table='radiology_type_categories';

    protected $fillable = ['en_name','ar_name'];



    public function radiology_types(){
        return $this->hasMany(RadiologyType::class,'type_group_id','id');
    }
}

app/Http/Controllers/RadiologyTypeCategoryController.php
<?php
namespace App\Http\Controllers;

use App\RadiologyTypeCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;


class RadiologyTypeCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $radiologyCats = RadiologyTypeCategory::all();
        return view('radiologytypecategories.index',compact('radiologyCats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('radiologytypecategories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dbSuccsess = false;
        $error = 'Unknown error - Store';

        DB::beginTransaction();
        try{
            RadiologyTypeCategory::create($request->input());
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                //DB::rollback();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cat = RadiologyTypeCategory::find($id);
        return view('radiologytypecategories.show',compact('cat'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cat = RadiologyTypeCategory::find($id);
        return view('radiologytypecategories.edit',compact('cat'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cat = RadiologyTypeCategory::find($id);

        $dbSuccsess = false;

        $error = 'Unknown error - Store';

        DB::beginTransaction();
        try {
            $cat->update($request->input());
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $cat = RadiologyTypeCategory::find($id);

        $dbSuccsess = false;

        $error = 'Unknown error - Store';

        DB::beginTransaction();
        try {
            $cat->delete();
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }
}

resources/views/radiologytypecategories/create.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Create New Radiology Type </b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>Radiology Type</b> Was Not Created.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Create new Radiology Type!</h4>
        <b>You Could Create new Radiology Type</b> to group your services.
    </div>



<div class="col-md-12">
    <div class="panel panel-success">
        <div class="panel-heading"> Create New Radiology Type </div>
        <div class="panel-wrapper collapse in" aria-expanded="true">
            <div class="panel-body" style="background-color: whitesmoke;">
            <div class="panel-body form">
                <form class="form" method="post" action="{{route('radiologytypecategories.store')}}">
                    {{ csrf_field() }}
                    @include('radiologytypecategories.fields')
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <a href="{{route('radiologytypecategories.index')}}" style="color:white;" class="btn btn-default">Cancel</a>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
</div>

@stop
@section('script')
    <script>

        $(document).ready(function(){
            onlyEnglish($('#en_name'));
            onlyArabic($('#ar_name'));
        });
    </script>
@stop

resources/views/radiologytypecategories/edit.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Update Radiology Type</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>Radiology Type</b> Was Not Updated.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Edit Radiology Type!</h4>
        <b>You Could Edit </b>Radiology Type Info.
    </div>

    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading"> Edit Radiology Type </div>
            <div class="panel-wrapper collapse in" aria-expanded="true">
                    <div class="panel-body form">
                            {!!Form::open(['method' => 'patch','route' => ['radiologytypecategories.update', $cat->id]])!!}
                            {{ csrf_field() }}

                        @include('radiologytypecategories.fields')

                        <div class="form-actions">
                                <button type="submit" class="btn btn-success">Submit</button>
                            <a href="{{route('radiologytypecategories.index')}}" style="color:white;" class="btn btn-default">Cancel</a>
                            </div>
                            {!!Form::close()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/radiologytypecategories/fields.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label>Radiology Type (English)</label>
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="flag-icon flag-icon-us"></span>
                </span>
                <input type="text" id="en_name" class="form-control" name="en_name" value="{{(isset($cat) ? $cat->en_name : '')}}" placeholder="Radiology Type (English)" required>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label>Radiology Type (Arabic)</label>
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="flag-icon flag-icon-eg"></span>
                </span>
                <input type="text" id="ar_name" class="form-control" name="ar_name" value="{{(isset($cat) ? $cat->ar_name : '')}}" placeholder="Radiology Type (Arabic)" required>
            </div>
        </div>
    </div>
</div>

resources/views/radiologytypecategories/index.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Delete Radiology Type</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>Radiology Type</b> Was Not Deleted.
    </div>
    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Create Radiology Types!</h4>
        <b>You Could Create Radiology Types</b> for the Center.
    </div>

    <a class="btn btn-success" href="{{route('radiologytypecategories.create')}}">
        <i class="fa fa-plus"></i> Add New Radiology Type
    </a>
    <br>
    <hr>
<table id="radiologytypecategories" class="table display" width="100%" cellspacing="0">
    <thead>
    <tr>
        <th>#</th>
        <th>Radiology Type - English</th>
        <th>Radiology Type - Arabic</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <th>#</th>
        <th>Radiology Type - English</th>
        <th>Radiology Type - Arabic</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </tfoot>
    <tbody>
        @php $i=1; @endphp
        @foreach($radiologyCats as $cat)
            <tr>
                <td>{{$i++}}</td>
                <td><a href="{{route('radiologytypecategories.show',$cat->id)}}">{{$cat->en_name}}</a></td>
                <td><a href="{{route('radiologytypecategories.show',$cat->id)}}">{{$cat->ar_name}}</a></td>
                <td>
                    <a href="{{route('radiologytypecategories.edit',$cat->id)}}" Class="btn btn-info">
                        <i Class="fa fa-lg fa-pencil"></i>
                    </a>
                </td>
                <td>
                    {!!Form::open(['method' => 'delete','route' => ['radiologytypecategories.destroy', $cat->id]])!!}
                    {{ csrf_field() }}
                    <button type="submit" Class="btn btn-danger">
                        <i Class="fa fa-lg fa-trash"></i>
                    </button>
                    {!!Form::close()!!}
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

@stop
@section('script')
<script>
    $(document).ready(function () {

        $('#radiologytypecategories').DataTable();
    });
</script>
@stop

resources/views/radiologytypecategories/show.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Radiology Types!</h4>
        <b>You Could Create New radiology Type</b> for the Center.
    </div>

    <a class="btn btn-success" href="{{route('radiologytypecategories.create')}}">
        <i class="fa fa-plus"></i> Create New Radiology Type
    </a>
    <br>
    <hr>

    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading"> Radiology Type Details </div>
            <div class="panel-wrapper collapse in" aria-expanded="true">
                <div class="panel-body" style="background-color: whitesmoke;">
                    <div class="panel-body form">

                            @include('radiologytypecategories.fields')

                        <div class="form-actions">
                            <div class="form-actions">
                                <a href="{{route('radiologytypecategories.edit',$cat->id)}}" Class="btn btn-info" style="color: white;">
                                    <i Class="fa fa-lg fa-pencil"></i> Edit
                                </a>
                                <a href="{{route('radiologytypecategories.index')}}" style="color:white;" class="btn btn-default">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('script')
    <script>
        $(document).ready(function(){
            $("input").prop('disabled', true);
        });
    </script>
@stop