routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('reportPreview', 'center_reportController@reportPreview');
Route::group(['middleware'=>'auth'],function(){
    Route::get('/', function () {
        return view('home');
    })->name('home');
//    Route::any('user/create','UserController@create')->name('user.store');
//    Route::get('user','UserController@index')->name('user.index');
    Route::resource('user', 'UserController');
    Route::resource('patientrequests', 'PatientRequestController');
    Route::any('confirm', 'PatientRequestController@confirmRequestEdit');
    Route::any('updateconfirm', 'PatientRequestController@confirmRequestUpdate');
    Route::any('result', 'PatientRequestController@resultCreate');
    Route::any('resultStore', 'PatientRequestController@resultStore');
    Route::resource('radiologytypecategories','RadiologyTypeCategoryController');
    Route::resource('radiologytypes','RadiologyTypeController');
    Route::resource('centers','CentersController');
    /* Lab test*/
    Route::resource('labrequests', 'RequestController');
    Route::any('updateRefuserequest','RequestController@updateRefuse')->name('requests.updateRefuserequest');
    Route::any('sortnamerequest','RequestController@sortname')->name('requests.sortnamerequest');
    Route::any('sortdaterequest','RequestController@sortdate')->name('requests.sortdaterequest');
    Route::any('sortlocationrequest','RequestController@sortlocation')->name('requests.sortlocationrequest');
    Route::any('sortstatusrequest','RequestController@sortstatus')->name('requests.sortstatusrequest');
    Route::any('storerequest','RequestController@sortstatus')->name('requests.storerequest');
    
    /*End Lab test*/
    Route::any('/reportreportAjax','center_reportController@reportAjax');

    Route::resource('', 'HomeController');
    Route::resource('centerresponses', 'CenterResponseController');
    Route::any('updateRefuse','PatientRequestController@updateRefuse')->name('patientrequests.updateRefuse');
    Route::any('sortname','PatientRequestController@sortname')->name('patientrequests.sortname');
    Route::any('sortdate','PatientRequestController@sortdate')->name('patientrequests.sortdate');
    Route::any('sortlocation','PatientRequestController@sortlocation')->name('patientrequests.sortlocation');
    Route::any('sortstatus','PatientRequestController@sortstatus')->name('patientrequests.sortstatus');

    Route::any('/reportAjax','PatientRequestController@reportAjax');
    Route::any('/notifiy','PatientRequestController@notifiy');
    Route::any('/notifiycenter','CenterResponseController@notifiycenter');
    Route::any('/notifiyresult','CenterResponseController@notifiyresult');

    Route::get('reports/statusgroup','ReportsController@statusReports')->name('reports.statusgroup');

Route::any('/reportuploads','PatientRequestController@reportuploads');

    Route::resource('urlgroups', 'UrlGroupController');
    Route::resource('urls', 'UrlController');
    Route::resource('usertypes', 'UserTypeController');
    Route::any('batchUpdate','UserTypeController@batchUpdate')->name('usertypes.batchUpdate');
    Route::post('language-switcher','LanguageController@switchLanguage');
    Route::post('/language/',array(
            'before' => 'csrf' ,
            'as' => 'language-switcher' ,
            'uses' => 'LanguageController@switchLanguage'
        )
    );
});


Route::get('/login', function () {
    return view('auth.login');
});

Route::group(['namespace'=>'Auth'],function(){
    Route::post('/login', ['uses'=>'LoginController@login'])->name('login.post');
    Route::get('/logout', ['uses'=>'LoginController@logout'])->name('auth.logout');
});

app/Center.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Center extends Model
{
    protected $table = 'centers';
    protected $fillable = ['name','address','map_location'];

    public function phones(){
        return $this->hasMany(CenterPhone::class,'center_id','id');
    }

    public function responses(){
        return $this
            ->belongsToMany(CenterResponse::class,'response_centers','center_id','response_id')
            ->withPivot(['arrive_datetime'])
            ->withTimestamps();
    }
}

app/Http/Controllers/CentersController.php
<?php
namespace App\Http\Controllers;

use App\Center;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CentersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $centers = Center::all();
        return view('centers.index',compact('centers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('centers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dbSuccsess = false;

        $error = 'Unknown error - Store';
        DB::beginTransaction();
        try{
            Center::create($request->input());
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                //DB::rollback();
                return redirect()->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $center = Center::find($id);
        return view('centers.show',compact('center'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $center = Center::find($id);
        return view('centers.edit',compact('center'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $center = Center::find($id);
        $dbSuccsess = false;

        $error = 'Unknown error - Store';

        DB::beginTransaction();
        try {
            $center->update($request->input());
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $center = Center::find($id);

        $dbSuccsess = false;

        $error = 'Unknown error - destroy';

        DB::beginTransaction();
        try {
            $center->delete();
            $dbSuccsess = true;
        }catch(Exception $ex)
        {
            $error = $ex->getMessage();
        }finally
        {
            if($dbSuccsess)
            {
                DB::commit();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess);
            }
            else{
                DB::rollback();
                return redirect()
                    ->back()
                    ->with( 'db' , $dbSuccsess)
                    ->with( 'error' , $error);
            }
        }
    }
}

resources/views/centers/create.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Create New Branch </b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>Branch</b> Was Not Created.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Create new Branch!</h4>
        <b>You Could Create new Branch</b> for the Center.
    </div>

    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading"> Create New Center Branch </div>
            <div class="panel-wrapper collapse in" aria-expanded="true">
                <div class="panel-body" style="background-color: whitesmoke;">
                    <div class="panel-body form">
                        <form class="form" method="post" action="{{route('centers.store')}}">
                            {{ csrf_field() }}
                            @include('centers.fields')
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <a href="{{route('centers.index')}}" style="color:white;" class="btn btn-default">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop

resources/views/centers/edit.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Update Branch Info</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>Branch</b> Was Not Updated.
    </div>

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Edit Center Branch!</h4>
        <b>You Could Edit </b> Branch Info.
    </div>

    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading"> Edit Center Branch </div>
            <div class="panel-wrapper collapse in" aria-expanded="true">
                <div class="panel-body" style="background-color: whitesmoke;">
                    <div class="panel-body form">
                        {!!Form::open(['method' => 'patch','route' => ['centers.update', $center->id]])!!}
                        {{ csrf_field() }}
                            @include('centers.fields')
                            <div class="form-actions">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <a href="{{route('centers.index')}}" style="color:white;" class="btn btn-default">Cancel</a>
                            </div>
                        {!!Form::close()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@stop
@section('script')
    <script>

        $(document).ready(function(){
            onlyEnglish($('#en_name'));
            onlyArabic($('#ar_name'));
        });
    </script>
@stop

resources/views/centers/fields.blade.php
@section('style')

@stop

<div class="row">
    <div class="row">
        <div class="col-md-9">
            <div class="form-group">
                <label>Center Address</label>
                <div class="input-group">
                <span class="input-group-addon">
                    <i class="fa fa-map"></i>
                </span>
                    <input type="text" class="form-control" id="address" name="address" placeholder="Address" value="{{(isset($center->address) ? $center->address : '')}}" required>

                    {{--<input type="text" id="latitude"  hidden/>--}}
                    {{--<input type="text" id="longitude"  hidden/>--}}
                    {{--<input type="text" name="map_location" id="map_location" hidden/>--}}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label>Center Name</label>
                <div class="input-group">
                <span class="input-group-addon">
                    <span class="fa fa-building"></span>
                </span>
                    <input type="text" id="name" class="form-control" name="name" value="{{(isset($center->name) ? $center->name : '')}}" placeholder="Radiology Type (English)" required>
                </div>
            </div>
        </div>
    </div>
</div>

@section('script')

    {{--<script src="https://maps.googleapis.com/maps/api/js?sensor=false?libraries=places&key=AIzaSyB9bD6FNx_faqcgU9uOoD9NykTYUxsgsmw"></script>--}}

    {{--<script>--}}
        {{--var x,y;--}}
        {{--function showResult(result) {--}}
            {{--x = result.geometry.location.lat();--}}
            {{--y = result.geometry.location.lng();--}}
            {{--document.getElementById('latitude').value = x;--}}
            {{--document.getElementById('longitude').value = y;--}}
        {{--}--}}

        {{--function getLatitudeLongitude(callback, address) {--}}
            {{--// If adress is not supplied, use default value 'Ferrol, Galicia, Spain'--}}
            {{--address = address || 'Alexandria, Egypt';--}}
            {{--// Initialize the Geocoder--}}
            {{--geocoder = new google.maps.Geocoder();--}}
            {{--if (geocoder) {--}}
                {{--geocoder.geocode({--}}
                    {{--'address': address--}}
                {{--}, function (results, status) {--}}
                    {{--if (status == google.maps.GeocoderStatus.OK) {--}}
                        {{--callback(results[0]);--}}
                    {{--}--}}
                {{--});--}}
            {{--}--}}
        {{--}--}}

        {{--var inpt = document.getElementById('btn');--}}

        {{--document.getElementById('address').addEventListener("blur", function () {--}}
            {{--var address = document.getElementById('address').value;--}}
            {{--getLatitudeLongitude(showResult, address);--}}
            {{--var map = document.getElementById('latitude').value+','+document.getElementById('longitude').value;--}}
            {{--document.getElementById('map_location').value = map;--}}
        {{--});--}}

    {{--</script>--}}
    {{--<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>--}}
    {{--<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCOJfU-kvBtYWP31_WlYcSbZ_w4qI8bH8g&callback=initMap"--}}
            {{--type="text/javascript"></script>--}}
@stop

resources/views/centers/index.blade.php
@extends('layout')
@section('content')

    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif
    <div id="alert-success" class="myadmin-alert myadmin-alert-img alert-success myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>You done it!</h4>
        <b>Delete Branch</b> Was Done Successfully.
    </div>

    <div id="alert-fail" class="myadmin-alert myadmin-alert-img alert-danger myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Sudden Failure, Sorry!</h4>
        <b>Branch</b> Was Not Deleted.
    </div>

    <a class="btn btn-success" href="{{route('centers.create')}}">
        <i class="fa fa-plus"></i> Add New Branch
    </a>
    <br>
    <hr>
    <table id="centers" class="table display" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>#</th>
            <th>Center</th>
            <th>Address</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>#</th>
            <th>Center</th>
            <th>Address</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </tfoot>
        <tbody>
        @php $i=1; @endphp
        @foreach($centers as $center)
            <tr>
                <td>{{$i++}}</td>
                <td><a href="{{route('centers.show',$center->id)}}">{{$center->name}}</a></td>
                <td>{{$center->address}}</td>
                <td>
                    <a href="{{route('centers.edit',$center->id)}}" Class="btn btn-info">
                        <i Class="fa fa-lg fa-pencil"></i>
                    </a>
                </td>
                <td>
                    {!!Form::open(['method' => 'delete','route' => ['centers.destroy', $center->id]])!!}
                    {{ csrf_field() }}
                    <button type="submit" Class="btn btn-danger">
                        <i Class="fa fa-lg fa-trash"></i>
                    </button>
                    {!!Form::close()!!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

@stop
@section('script')
    <script>
        $(document).ready(function () {

            $('#centers').DataTable();
        });
    </script>
@stop

resources/views/centers/show.blade.php
@extends('layout')
@section('content')
    @if(session()->has('db'))
        <input type="text" value="{{session()->get('db')}}" id="db" hidden />
    @endif

    <div id="alert-info" class="myadmin-alert myadmin-alert-img alert-info myadmin-alert-top-right"> <img src="{{asset('images/logo.png')}}" class="img" alt="img"><a href="#" class="closed">&times;</a>
        <h4>Welcome To Create Center Branch!</h4>
        <b>You Could Create New Branch</b> for the Center.
    </div>

    <a class="btn btn-success" href="{{route('centers.create')}}">
        <i class="fa fa-plus"></i> Add New Branch
    </a>
    <br>
    <hr>

    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading"> Radiology Item Details </div>
            <div class="panel-wrapper collapse in" aria-expanded="true">
                <div class="panel-body" style="background-color: whitesmoke;">
                    <div class="panel-body form">

                        @include('centers.fields')

                        <div class="form-actions">
                            <div class="form-actions">
                                <a href="{{route('centers.edit',$center->id)}}" Class="btn btn-info" style="color: white;">
                                    <i Class="fa fa-lg fa-pencil"></i> Edit
                                </a>
                                <a href="{{route('centers.index')}}" style="color:white;" class="btn btn-default">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('script')
    <script>
        $(document).ready(function(){
            $("input").prop('disabled', true);
            $("textarea").prop('disabled', true);
        });
    </script>
@stop